import type { EditorThemeClasses } from 'lexical';

export const LexicalTheme: EditorThemeClasses = {
  ltr: 'text-left',
  rtl: 'text-right',
  placeholder: 'text-dim pointer-events-none absolute left-4 top-4 select-none text-xs font-medium',
  paragraph: 'mb-4 text-xs leading-relaxed text-slate-200 last:mb-0',
  quote:
    'my-4 border-l-2 border-white/40 bg-white/[0.03] py-2 pl-4 pr-3 text-xs italic text-slate-300 rounded-r-lg',
  heading: {
    h1: 'h-display my-5 text-xl font-bold text-white',
    h2: 'h-display my-4 text-lg font-bold text-soft',
    h3: 'h-display my-3 text-base font-semibold text-soft',
  },
  list: {
    nested: {
      listitem: 'list-none',
    },
    ol: 'my-3 ml-5 list-decimal space-y-1 text-xs text-slate-200',
    ul: 'my-3 ml-5 list-disc space-y-1 text-xs text-slate-200',
    listitem: 'leading-relaxed',
  },
  image: 'editor-image',
  link: 'text-white underline underline-offset-4 decoration-white/40 hover:decoration-white transition-colors cursor-pointer',
  text: {
    bold: 'font-bold text-white',
    italic: 'italic text-slate-100',
    overflowed: 'editor-text-overflowed',
    hashtag: 'editor-text-hashtag',
    underline: 'underline underline-offset-4',
    strikethrough: 'line-through text-dim',
    underlineStrikethrough: 'underline line-through',
    code: 'rounded bg-white/10 px-1.5 py-0.5 font-mono text-[11px] text-goldlight border border-white/15',
  },
  code: 'my-4 block overflow-x-auto rounded-xl border border-white/15 bg-black/70 p-4 font-mono text-xs text-slate-300',
  codeHighlight: {
    atrule: 'text-purple-400',
    attr: 'text-blue-400',
    boolean: 'text-amber-400',
    builtin: 'text-emerald-400',
    cdata: 'text-slate-500 italic',
    char: 'text-amber-300',
    class: 'text-cyan-400',
    'class-name': 'text-cyan-400',
    comment: 'text-slate-500 italic',
    constant: 'text-amber-400',
    deleted: 'text-red-400',
    doctype: 'text-slate-500 italic',
    entity: 'text-purple-400',
    function: 'text-blue-300',
    important: 'text-red-400 font-bold',
    inserted: 'text-emerald-400',
    keyword: 'text-purple-400 font-semibold',
    number: 'text-amber-300',
    operator: 'text-pink-400',
    prolog: 'text-slate-500 italic',
    property: 'text-blue-400',
    punctuation: 'text-slate-400',
    regex: 'text-red-300',
    selector: 'text-emerald-400',
    string: 'text-amber-300',
    symbol: 'text-amber-400',
    tag: 'text-pink-400',
    url: 'text-blue-400 underline',
    variable: 'text-rose-400',
  },
};
